### ISSUE TITLE
Has a Error!

### ISSUE THREAD

**Issue by jerviscui** [cezarypiatek/SmartCodeGenerator#8]
ClassLibrary1 project is .net core 3.0 liabrary.

1. install SmartCodeGenerator.Engine v1.4.23
2. install MappingGenerator.OnBuildGenerator v1.22.1.18

And then rebuild project, there is a mistake:

> “C:\Users\cuizj\.nuget\packages\smartcodegenerator.engine\1.4.23\build\/../tools/SmartCodeGenerator.Engine.exe -p E:\Project\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj -o E:\Project\ConsoleApp1\ClassLibrary1\obj\Debug\netcoreapp3.0\ -g C:\Users\cuizj\.nuget\packages\mappinggenerator.onbuildgenerator\1.22.1.18\build\/../tools/MappingGenerator.OnBuildGenerator.dll” exit code: -532462766。	ClassLibrary1	C:\Users\cuizj\.nuget\packages\smartcodegenerator.engine\1.4.23\build\SmartCodeGenerator.Engine.targets	11	

I have run this command in PowerShell,

> C:\Users\cuizj\.nuget\packages\smartcodegenerator.engine\1.4.23\build\/../tools/SmartCodeGenerator.Engine.exe -p E:\Project\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj -o E:\Project\ConsoleApp1\ClassLibrary1\obj\Debug\netcoreapp3.0\ -g C:\Users\cuizj\.nuget\packages\mappinggenerator.onbuildgenerator\1.22.1.18\build\/../tools/MappingGenerator.OnBuildGenerator.dll
Run with the following options:
ProjectPath -> E:\Project\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj
OutputPath -> E:\Project\ConsoleApp1\ClassLibrary1\obj\Debug\netcoreapp3.0\
GeneratorPaths -> C:\Users\cuizj\.nuget\packages\mappinggenerator.onbuildgenerator\1.22.1.18\build\/../tools/MappingGenerator.OnBuildGenerator.dll
Available msbuild instances
Selected msbuild .NET Core SDK 5.0.103
Selected msbuild .NET Core SDK 5.0.103
Evaluate        0:00.0646270    ClassLibrary1.csproj
处理文件“E:\Project\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj”时 Msbuild 失败，出现消息: Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GenerateAsync' in type 'MappingGenerator.OnBuildGenerator.OnBuildMappingGenerator' from assembly 'MappingGenerator.OnBuildGenerator, Version=1.22.1.18, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at SmartCodeGenerator.Engine.FileSystemGeneratorsSource.<>c__DisplayClass2_0.<GetGeneratorTypes>b__0(String x) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Engine\FileSystemGeneratorsSource.cs:line 24
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SmartCodeGenerator.Engine.FileSystemGeneratorsSource.GetGeneratorTypes() in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Engine\FileSystemGeneratorsSource.cs:line 21
   at SmartCodeGenerator.Core.GeneratorPluginProvider..ctor(IGeneratorsSource generatorsSource) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Core\GeneratorPluginProvider.cs:line 16
   at SmartCodeGenerator.Core.CompilationGenerator..ctor(ITransformedDocumentPersister documentPersister, IGeneratorsSource generatorsSource, ProgressReporter progressReporter) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Core\CompilationGenerator.cs:line 19
   at SmartCodeGenerator.Engine.Program.Main(String[] args) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Engine\Program.cs:line 40
   at SmartCodeGenerator.Engine.Program.<Main>(String[] args)
System.TypeLoadException: Method 'GenerateAsync' in type 'MappingGenerator.OnBuildGenerator.OnBuildMappingGenerator' from assembly 'MappingGenerator.OnBuildGenerator, Version=1.22.1.18, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GenerateAsync' in type 'MappingGenerator.OnBuildGenerator.OnBuildMappingGenerator' from assembly 'MappingGenerator.OnBuildGenerator, Version=1.22.1.18, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at SmartCodeGenerator.Engine.FileSystemGeneratorsSource.<>c__DisplayClass2_0.<GetGeneratorTypes>b__0(String x) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Engine\FileSystemGeneratorsSource.cs:line 24
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SmartCodeGenerator.Engine.FileSystemGeneratorsSource.GetGeneratorTypes() in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Engine\FileSystemGeneratorsSource.cs:line 21
   at SmartCodeGenerator.Core.GeneratorPluginProvider..ctor(IGeneratorsSource generatorsSource) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Core\GeneratorPluginProvider.cs:line 16
   at SmartCodeGenerator.Core.CompilationGenerator..ctor(ITransformedDocumentPersister documentPersister, IGeneratorsSource generatorsSource, ProgressReporter progressReporter) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Core\CompilationGenerator.cs:line 19
   at SmartCodeGenerator.Engine.Program.Main(String[] args) in C:\projects\smartcodegenerator\src\SmartCodeGenerator.Engine\Program.cs:line 40
   at SmartCodeGenerator.Engine.Program.<Main>(String[] args)
System.TypeLoadException: Method 'GenerateAsync' in type 'MappingGenerator.OnBuildGenerator.OnBuildMappingGenerator' from assembly 'MappingGenerator.OnBuildGenerator, Version=1.22.1.18, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by cezarypiatek** [comment]
Looks like the same problem as with https://github.com/cezarypiatek/MappingGenerator/issues/166
I guess this somehow related to .net 5 SDK because there was nothing changed in SmartCodeGenerator for a long time. I need to take a look at this.
